version: '3.9'
services:
  prometheus:
    image: prom/prometheus:v2.47.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - prometheus:/prometheus
    networks:
      - infrastructure
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --log.format=json
      - --web.enable-remote-write-receiver
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
      placement:
        constraints:
          - "node.role==manager"
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        prometheus.job: prometheus
        prometheus.port: 9090
        prometheus.path: /metrics
        traefik.enable: 'false'
        traefik.http.routers.prometheus.rule: Host(`prometheus.gavanlamb.com`)
        traefik.http.routers.prometheus.entrypoints: websecure
        traefik.http.routers.prometheus.tls.certresolver: letsencrypt
        traefik.http.routers.prometheus.service: prometheus
        traefik.http.services.prometheus.loadBalancer.server.port: 9090
    logging:
      options:
        loki-external-labels: "job=prometheus"
  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.6.1
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.platform == linux"
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        prometheus.job: node_exporter
        prometheus.port: 9100
        prometheus.path: /metrics
    command:
      - --path.rootfs=/host
      - --log.format=json
    pid: host
    environment:
      - NODE_ID={{.Node.ID}}
    networks:
      - infrastructure
    volumes:
      - /:/host:ro,rslave
    logging:
      options:
        loki-external-labels: "job=node_exporter"
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    networks:
      - infrastructure
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      placement:
        constraints:
          - "node.labels.platform==linux"
      rollback_config:
        parallelism: 0
        failure_action: continue
        order: stop-first
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      labels:
        prometheus.job: cadvisor
        prometheus.port: 8080
        prometheus.path: /metrics
    logging:
      options:
        loki-external-labels: "job=cadvisor"

configs:
  prometheus_config:
    file: config/prometheus.yml
    name: prometheus_config

volumes:
  prometheus:
    name: prometheus
    driver_opts:
      type: "nfs"
      o: "addr=192.168.50.19,rw,noatime,rsize=8192,wsize=8192,tcp,timeo=14"
      device: ":/share/docker/prometheus"

networks:
  infrastructure:
    name: infrastructure
    external: true
