global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: docker
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: nodes
    relabel_configs:
      - source_labels: [__meta_dockerswarm_node_address]
        target_label: __address__
        replacement: $1:9323
      - source_labels: [__meta_dockerswarm_node_hostname]
        target_label: instance
  - job_name: windows_exporter
    scrape_interval: 5s
    static_configs:
      - targets: [ '192.168.50.18:9182' ]
  - job_name: dockerswarm
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      - source_labels: [ __meta_dockerswarm_task_desired_state ]
        regex: running
        action: keep
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        regex: .+
        action: keep
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        target_label: job
      - source_labels: [ __meta_dockerswarm_node_hostname ]
        target_label: docker_node
      - regex: __meta_dockerswarm_service_label_prometheus_(.+)
        action: labelmap
        replacement: $1
      - source_labels: [ __address__, __meta_dockerswarm_service_label_prometheus_port ]
        action: replace
        regex: (.+)(?::\d+);(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_path ]
        action: replace
        target_label: __metrics_path__

tracing:
  client_type: grpc
  endpoint: tempo:4317
  sampling_fraction: 0
  insecure: true
  compression: gzip
  timeout: 10s
